services:
  frontend:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_USERNAME=${VITE_USERNAME}
        - VITE_PASSWORD=${VITE_PASSWORD}
        - VITE_SYSTEM_LOGS_URL=${VITE_SYSTEM_LOGS_URL}
        - VITE_TEST_MODE=${VITE_TEST_MODE}
        - VITE_ENVIRONMENT=${VITE_ENVIRONMENT}
    container_name: valace_opac_admin_frontend
    ports:
      - "3001:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
